# Info
info:
  title: Doflake
  author: Doflake
  favicon: https://cdn.jsdelivr.net/gh/doflake/Picture/Favicon/1.jpg

# Menu
menu:
  Home: 
    name: 主页
    link: /
  Archives:
    name: 归档
    link: /archives
  Github: 
    name: Github
    link: https://github.com/doflake/

# Sidebar
sidebar:
  enable: false
  names:
    name: 
    link:

# Mathjax
## Using:
## 1. npm uninstall hexo-renderer-marked --save 
## 2. npm install hexo-renderer-kramed --save
## Study:
## https://www.jianshu.com/p/7ab21c7f0674  (解决冲突)
## https://spacefan.github.io/2018/06/27/hexo-MathJax/  (mathjax.ejs以及调用)
mathjax:
  enable: true

    