# ==================================================================================================
# < doflake > hexo themes
# ================================================================================================== 

# ================================================================================================== 
# < Info > 基础设置 
# ================================================================================================== 
info:

# ================================================================================================== 
# < aside > 侧边栏
# ================================================================================================== 
aside:
  author:
    avatar: https://cdn.jsdelivr.net/gh/doflake/Picture/Card/Avatar-Dove.jpg 
    title: doflake
    subtitle: Hexo Themes

# ================================================================================================== 
# < Nav Bar> 导航栏 (/layout/_common/navigation-bar.ejs)
# ================================================================================================== 

# ================================================================================================== 
# < Alert > 弹窗 (/layout/_common/alert.ejs)
# ================================================================================================== 
alert:
  index_welcome:
    enable: true
    content: "欢迎来到 doflake 的小窝"


color:
  primary: "#9049ff"
  accent: "#44D7B6"
  link:
    before: "#03A9F4"
    hover: "#44D7B6"
  title:
    before: "#C60055"
    hover: "#9049FF"
  name: "#FF4081"



    
